version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - ENDPOINT_URL=${ENDPOINT_URL}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
    volumes:
      - ./static:/app/static
      - ./templates:/app/templates
    restart: unless-stopped 